"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""

import functools as functools


class TriangleNumber:
    current_count = 0
    current_increment = 0

    def next(self):
        self.current_increment = self.current_increment + 1
        self.current_count = self.current_count + self.current_increment
        return self.current_count


def factors(n):
    return set(functools.reduce(list.__add__,
                                ([i, n // i] for i in range(1, int(pow(n, 0.5) + 1)) if n % i == 0)))


tnum = TriangleNumber()
dividors = 0
num = 0

while (dividors < 500):
    num = tnum.next()
    facts = factors(num)
    dividors = len(facts)

print("the value of the first triangle number to have over five hundred divisors:%s" % num)
