""""

Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
"""

MAX = 4_000_000
count = 0
computed = 0
prev1 = 0
prev2 = 1
while (computed <= MAX):
    computed = prev1 + prev2
    prev1 = prev2
    prev2 = computed
    if computed % 2 == 0:
        count = count + computed

print("sum of even-valued terms: %s" % count)
